name: Create Release

on:
    push:
        branches:
            - main
            - feature/versioning

jobs:
    release:
        name: Create release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Extract release notes
              id: extract-release-notes
              uses: ffurrer2/extract-release-notes@v1
            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: gh release create --notes '${{ steps.extract-release-notes.outputs.release_notes }}' --title '${{ steps.extract-release-notes.outputs.release_title }}'
